name: build library

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-npm-gulp:
    runs-on: ubuntu-20.04
    name: Build library - npm/gulp
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node 10
        uses: actions/setup-node@v2
        with:
          node-version: '10'

      - name: Build library
        run: |
          npm install
          gulp

      - name: Archive library
        uses: actions/upload-artifact@v2
        with:
          name: minified-library-npm-gulp
          path: web/openhab-grafana.js
          if-no-files-found: error

  build-maven:
    runs-on: ubuntu-20.04
    name: Build library - Maven
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build library
        run: mvn clean package

      - name: Archive library
        uses: actions/upload-artifact@v2
        with:
          name: minified-library-maven
          path: web/openhab-grafana.js
          if-no-files-found: error
